In [42]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [43]:
dataset = { "score" :[480,490,510,510,530,550,610,640],
            "gpa":[2.7,2.9,3.3,2.9,3.1,3.0,3.2,3.7]
           }

In [44]:
dataset

{'score': [480, 490, 510, 510, 530, 550, 610, 640],
 'gpa': [2.7, 2.9, 3.3, 2.9, 3.1, 3.0, 3.2, 3.7]}

In [45]:
dataframe = pd.DataFrame(dataset)
dataframe

score  gpa
0    480  2.7
1    490  2.9
2    510  3.3
3    510  2.9
4    530  3.1
5    550  3.0
6    610  3.2
7    640  3.7

In [46]:
X = dataframe['score'].values
y = dataframe['gpa'].values

In [47]:
X=X.reshape(-1,1)

In [48]:
# Splitting the dataset into Training and Test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=1/3, random_state=0)

# Printing the training and test sets (Optional)
print("X_train:\n", X_train)
print("y_train:\n", y_train)
print("X_test:\n", X_test)
print("y_test:\n", y_test)

X_train:
 [[640]
 [510]
 [480]
 [550]
 [530]]
y_train:
 [3.7 2.9 2.7 3.  3.1]
X_test:
 [[610]
 [510]
 [490]]
y_test:
 [3.2 3.3 2.9]


In [49]:
# Training the Simple Linear Regression Model
regressor = LinearRegression()
regressor.fit(X_train, y_train)


LinearRegression()

In [50]:
# Getting the Coefficient and Intercept
coefficient = regressor.coef_
intercept = regressor.intercept_

print("Coefficient (Slope):", coefficient[0])
print("Intercept:", intercept)


Coefficient (Slope): 0.0060762942779291566
Intercept: -0.2133514986376026


In [51]:
regressor.predict(([600],[700]))

array([3.43242507, 4.0400545 ])